theme: hugo-orbit-theme
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true
enableMissingTranslationPlaceholders: true
googleAnalytics: UA-146617747-1
languages:
  en:
    languageCode: en
    languageName: English
    weight: 1
  zh:
    languageCode: zh
    languageName: 中文
    weight: 2
  ja:
    languageCode: ja
    languageName: 日本語
    weight: 3

params:
  peering:
    enable: true
    icon: fa-globe
    description: |
      Peering with AS57429/AS212359 (Haraguroicha Internet Service)

      You can contact me with @Haraguroicha in Telegram
    info:
      - num: 57429
        name: Haraguroicha Internet Service
        db: https://www.peeringdb.com/net/25619
        as-set:
          - AS-HARAGUROICHA
        policy: Open
        prefix6:
          - 2a0e:8f02:f00e::/48
          - 2a0e:b107:1340::/44
          - 2a0f:607:1024::/48
          - 2602:feda:c10::/44
          - 2602:fc23:111::/48
        contact:
          name: 腹黒い茶
          url: https://t.me/Haraguroicha
      - num: 212359
        name: Haraguroicha Internet Service
        db: https://www.peeringdb.com/net/25619
        as-set:
          - AS-HARAGUROICHA
        policy: Open
        prefix6:
          - 2a0e:8f02:f00e::/48
          - 2a0e:b107:1340::/44
          - 2a0f:607:1024::/48
          - 2602:feda:c10::/44
          - 2602:fc23:111::/48
        contact:
          name: 腹黒い茶
          url: https://t.me/Haraguroicha
    locations:
      - origin: New Taipei, TW
        port: 100Mbps
        services:
          - WireGuard
          - GRE
          - IPSec
      - origin: Taipei, TW
        port: 100Mbps
        services:
          - WireGuard
          - GRE
          - IPSec
      - origin: Taichung, TW
        port: 100Mbps
        services:
          - GRE
          - IPSec
      - origin: Tokyo, JP
        port: 10Gbps
        services:
          - WireGuard
          - GRE
          - IPSec
      - origin: Fremont, US
        port: 1Gbps
        services:
          - direct in LL-IX
          - direct in Lambda Internet Exchange
    ix:
      - ixp: STUIX
        db: https://peeringdb.com/ix/3352
        port: 1Gbps
        addr:
          - 103.158.187.22
          - 2a0f:5707:ffe3::22
      - ixp: LL-IX
        db: https://peeringdb.com/ix/2343
        port: 1Gbps
        addr:
          - 5.101.92.218
          - 2001:678:4fc::92:218
      - ixp: Lambda Internet Exchange
        db: https://peeringdb.com/ix/3634
        port: 1Gbps
        addr:
          - 23.191.16.7
          - 2a0f:607:1070::7
  githubBase: https://github.com/Haraguroicha/Resume
  author: 腹黒い茶
  fb:
    app_id: 2444528935631510
    pages_id: 111936232493172
  og_image:
    image: https://avatars3.githubusercontent.com/u/1715541?v=4&s=420
    type: image/jpeg
    width: 420
    height: 420
  styles: main.sass
  contact:
    enable: true
    list:
      - class: email
        icon: fa-envelope
        url: mailto:m50gbmb@gmail.com
        title: m50gbmb@gmail.com
      - class: phone
        icon: fa-phone
        url: "tel:+886983604005"
        title: "+886-983-604-005"
      - class: gpg
        icon: fa-key
        url: //pgp.mit.edu/pks/lookup?search=0xBF78E2BAA68644F0
        title: A68644F0
      - class: website
        icon: fa-globe
        url: //haraguroicha.work
        title: haraguroicha.work
      - class: linkedin
        icon: fa-linkedin
        url: //www.linkedin.com/in/haraguroicha
        title: linkedin.com/in/haraguroicha
      - class: github
        icon: fa-github
        url: //github.com/Haraguroicha
        title: github.com/Haraguroicha
      - class: twitter
        icon: fa-twitter
        url: //twitter.com/haraguroicha
        title: "@haraguroicha"
  experiences:
    enable: true
    icon: fa-briefcase
  skills:
    enable: true
    icon: fa-rocket
    list:
      - skill: Golang
      - skill: Python
      - skill: Swift
      - skill: Objective-C
      - skill: Git
      - skill: C#
      - skill: Bash
      - skill: macOS
      - skill: Linux
      - skill: GitLab
      - skill: GitLab CI
      - skill: Docker
      - skill: Kubernetes
      - skill: Nginx
      - skill: PostgreSQL
      - skill: Oracle DB
      - skill: IBM DB2
      - skill: MySQL
      - skill: 3ds Max
      - skill: blender
  footer:
    copyright: 腹黒い茶

outputs:
  home: [ "HTML", "RSS" ]
