sudo: false
language: go
go:
  - 1.14.x
install:
  - go get --tags extended github.com/gohugoio/hugo
  - hugo version
branches:
  only:
  - master
script:
  - ./build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .build/
  on:
    branch: master
cache:
  directories:
    - $GOPATH/pkg/mod
