# fly.toml file generated for haraguroicha-work on 2022-12-09T23:23:05+08:00

app = "haraguroicha-work"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "nrt"

[env]
TZ = "Asia/Taipei"

[experimental]
auto_rollback = true

  [experimental.attached]
  secrets = { }

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 80
min_machines_running = 0
processes = [ "app" ]

[[services]]
internal_port = 8080
processes = [ "app" ]
protocol = "tcp"

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  timeout = "2s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
memory_mb = 256