title: Haraguroicha's Resume
theme: hugo-orbit-theme
languageCode: en-us
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true
enableMissingTranslationPlaceholders: true
googleAnalytics: UA-146617747-1

params:
  title: Resume / CV - Ming-Ray Hsu (腹黒い茶)
  short_title: Ming-Ray's Resume / CV
  githubBase: https://github.com/Haraguroicha/Resume
  description: Haraguroicha Resume/CV
  author: 腹黒い茶
  locale: en_US
  fb:
    app_id: 2444528935631510
    pages_id: 111936232493172
  og_image:
    image: https://avatars3.githubusercontent.com/u/1715541?v=4&s=420
    type: image/jpeg
    width: 420
    height: 420
  styles: main.sass
  profile:
    name: |
      Ming-Ray Hsu  
      腹黒い茶
    tagline: |
      * Systems Engineer
      * SRE
      * iOS Developer
    avatar: https://avatars3.githubusercontent.com/u/1715541?v=4&s=180
  contact:
    enable: true
    list:
      - class: email
        icon: fa-envelope
        url: mailto:m50gbmb@gmail.com
        title: m50gbmb@gmail.com
      - class: phone
        icon: fa-phone
        url: "tel:+886983604005"
        title: "+886-983-604-005"
      - class: gpg
        icon: fa-key
        url: //pgp.mit.edu/pks/lookup?search=0xBF78E2BAA68644F0
        title: A68644F0
      - class: website
        icon: fa-globe
        url: //haraguroicha.work
        title: haraguroicha.work
      - class: linkedin
        icon: fa-linkedin
        url: //www.linkedin.com/in/haraguroicha
        title: linkedin.com/in/haraguroicha
      - class: github
        icon: fa-github
        url: //github.com/Haraguroicha
        title: github.com/Haraguroicha
      - class: twitter
        icon: fa-twitter
        url: //twitter.com/haraguroicha
        title: "@haraguroicha"
  language:
    enable: true
    title: Languages
    list:
      - language: Chinese
        level: Native
      - language: English
        level: Read / Write / Speak
      - language: Japanese
        level: Read / Speak
  summary:
    enable: false
    icon: fa-user
    summary: ""
  experiences:
    enable: true
    icon: fa-briefcase
  jobs:
    list:
      - position: Systems Engineer
        company: TeamT5 Inc.
        dates: 2018-08 - Present
        location: Taipei, Taiwan
        details: |
          Manage private Virtual Machine Farms (VMF), office networking and infrastructures. Re-design/Relocate the server room layout to save the energy waste, and manage.

          * Use GitLab CI to manage private DNS config and record through config test and deploy stage
          * Set up the Polycom and SIP Phones via free version of Elastix PBX
          * Improve the network sensitivity by blocking cross VLAN communication capability to specified network
          * Monitoring the server and its services status by using Grafana to create a dashboard
          * Use BGP (Border Gateway Protocol) to make specified routing rules for route traffic to a dedicated address outbound
          * Lead to deploy virtual machine and virtual container into Proxmox VE Server
          * Planning networking for office relocation
          * Planning and integrate the Server Room for relocation to IDC
          * Lead to migrate Hardword RAID Storage Pools to Ceph Clusters
          * Lead and design VLAN policies and IP access list (IP ACL)
          * Lead to plan and migrate networking devices to enlarge the scaling from 400 concurrent hosts to 1500+

      - position: Site Reliability Engineer
        company: Rayark Inc.
        dates: 2017-12 - 2018-05
        location: Taipei, Taiwan
        details: |
          Deploy and manage the REST API Server Perform the load test and volume test on GKE (Google Cloud Kubernetes) and GCP (Google Compute Engine)

          * Deploy the REST API Server with the calculated HPA(Horizontal Pod Autoscaler) configuration
          * Re-Configure the GCP Firewall settings to preven database being unauthroized accessment
          * Perform load and volume test by rebuilding bandbox in whole system
          * Make Golang program to have more verbose for debugging (incl. CI/CD environment variables)
          * Tune CI/CD flow for GKE project deployment

      - position: Software Developer
        company: Koo Foundation Sun Yat-Sen Cancer Center (KFSYSCC)
        dates: 2013-07 - 2017-11
        location: Taipei, Taiwan
        details: |
          Consolidate team members' ideas to have problem solution through system architecture and/or framework. Improve workflow of management issues by using in-house developed software.

          * Maintain in-house GitLab server to have git repositories and CI/CD services been available for all designers.
          * Improve communication among colleagues and do cost analysis easier by using Redmine.
          * Lead a team to design and implement a WebAPI server, in 2014, to have the client library generation feature for JavaScript and Objective-C (iOS) written in C#, which makes the server be stable 3 and half years.
          * Promote the server in Python w/ SQL command cache feature to have in-line development, in 2017, which allows to update the command text w/o restart the server
          * Make higher maintainability among Windows Applications and Web Applications by integrating common business logics into WebAPI server
          * Provide centralized management tool for designers to test and read the self-generated manual on the WebAPI Server
          * Implement a codepage converting system on WebAPI server to convert Private Use Area (PUA) characters between BIG5 and UTF-8 by using iconv (UTF-8 and BIG5) codepage and CNS11643 mapping table
          * Create Docker image to strip the whole service into microservice architecture
          * Combined Python-based WebAPI server into Linux-based image with Nginx web server and uWSGI proxy which communicates between client and the WebAPI server
          * Administrate WebAPI server and manage software security and quality by using CI/CD for all projects
          * Administrate all merge requests and improve the software quality of projects by doing code review
          * Study the frontend and backend technology, then, provide training courses of development experience and suggestion to colleagues
          * Highlight low performance SQL commands, then, improve these defect by either rewriting command or modifying schemas on Oracle DB and PostgreSQL
          * Validate the services of security and compatibility on servers and then generate the management report of all customer devices by using [testssl.sh](https://testssl.sh)
          * Deploy MDM (Mobile Devices Management) to manage 180+ iOS devices to have in-house enterprise apps been pre-installed

      - position: System Administrator (part-time)
        company: National Taipei University of Nursing and Health Sciences (NTUNHS), Department of Information Management
        dates: 2011-07 - 2013-07
        location: Taipei, Taiwan
        details: |
          Deploy and administrate Active Directory in laboratory
      - position: Software Engineering Intern (part-time)
        company: Cathay General Hospital (C.G.H.)
        dates: 2007-07 - 2009-09
        location: Taipei, Taiwan
        details: |
          Use PHP, MySQL and IBM DB2 to design and develop an integrated Healthcare Information System (HIS) for taking care in-patient. (Note: this system was renamed to be i-Mobile Medical Information System formally and won the National Health Science and Technology Quality Bronze Award in 2013)
      - position: Solution Developer
        company: CPRTeam
        dates: 2011-08 - 2017-06
        location: Taipei, Taiwan
        details: |
          Configure wireless network to Internet network for conference with 500+ to 1500+ attendees

          * Provide network services for COSCUP, in 2013 at TICC, without being qualified hardwares, by building 36 Virtual Machines (m0n0wall software router) within 15 minutes to serve 1400+ attendees by 36 different configurations
          * Create Open Source Codes for projects, such as handheld radio asset management, in [CPRTeam's repository](https://github.com/CPRTeam)
  projects:
    enable: true
    icon: fa-archive
    intro: ""
    list:
      - title: OPass (CCIP Pass) app Developer
        url: https://github.com/CCIP-App
        tagline: |
          CCIP Pass (Community Check-in with Interactivity Project) app provides a self-checkin application on mobile to save manpower to check the attendee ticket, and let the attendees have more opportunities to interact with other features(e.g. Puzzle Game, Booth Reward Activity)

          * Develop [iOS version](https://github.com/CCIP-App/CCIP-iOS), [Pass landing page](https://github.com/CCIP-App/CCIP-Landing) and [administration dashboard page](https://github.com/CCIP-App/CCIP-Administration)
          * Used in COSCUP 2016, 2017, 2018, 2019, SITCON 2018, 2019, PyConTW 2018, g0v summit 2018 and HITCON CMT 2019
            * OPass app ([App Store](https://itunes.apple.com/app/id1436417025?mt=8))
  education:
    enable: true
    icon: fa-graduation-cap
    list:
      - college: National Taipei University of Nursing and Health Sciences (NTUNHS)
        degree: Master Degree, Department of Information Management
        dates: 2011 - 2013
        details: |
          * Study Healthcare and Informatics, Software Engineering
          * Study and develop a template system to read HL7 (Health Level 7) CDA® R2 (Clinical Document Architecture Release 2) XML into HTML5 Canvas directly and layout a WYSIWYG (What You See Is What You Get) document by using Web Component technologies
      - college: |
          Tzu Chi College of Technology (TCCT)  
          Tzu Chi University of Science and Technology (TCUST, Renamed in 2015)
        degree: Bachelor Degree, Department of Information Engineering and Informatics
        dates: 2007 - 2011
        details: |
          * Study Software Engineering and RFID related software development
          * Study HTML5 related software development, and create an interactive website w/o using any Flash technology
  skills:
    enable: true
    icon: fa-rocket
    list:
      - skill: Objective-C (All platform)
      - skill: Python
      - skill: Golang
      - skill: Git
      - skill: C#
      - skill: Bash
      - skill: macOS
      - skill: Linux
      - skill: GitLab
      - skill: GitLab CI
      - skill: Docker
      - skill: Kubernetes
      - skill: Nginx
      - skill: PostgreSQL
      - skill: Oracle DB
      - skill: IBM DB2
      - skill: MySQL
  footer:
    copyright: 腹黒い茶

outputs:
  home: [ "HTML", "RSS" ]
