name: Resume Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Taipei"
        timezoneMacos: "Asia/Taipei"
        timezoneWindows: "Taipei Standard Time"
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: "${{ vars.HUGO_BUILD_VERSION }}"
        extended: true
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Install jq
      run: sudo apt-get install -y jq
    - uses: actions/cache@v2
      with:
        path: /tmp/hugo_cache
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Build
      env:
        GO111MODULE: on
      run: ./build.sh
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: .build
        path: .build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .build
        force_orphan: true
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#    - uses: akhileshns/heroku-deploy@v3.12.12
#      with:
#        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#        heroku_email: ${{ secrets.HEROKU_EMAIL }}
#        branch: origin/gh-pages
#        buildpack: "https://github.com/heroku/heroku-buildpack-nginx.git"
